// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BuildingBricks.Inventory.Models;

public partial class VwProductInventory
{
    public string ProductId { get; set; }

    public string ProductName { get; set; }

    public int? ProductInventoryOnHand { get; set; }

    public int? ReservedCount { get; set; }
}